### ISSUE TITLE
Add me as contributor to project

### ISSUE THREAD

**Issue by svarnypetr** [n8s8/Hello-World-8#5]
If you want to have me adding pull requests directly to the code, then please add me as a contributor.

As a side note, `goOnce` does not need to be += as you switch only between 0 and 1 so it can also be just a boolean.

**Comment by n8s8** [comment]
Hi sir! Will do, I am currently working on my Networking, I will add you as soon as possible :).

**Comment by n8s8** [comment]
I have added you as a collaborator, I will now check your previous feedback, sorry for the delay sir.
